apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  #if you want to deploy on specific project, create project and provide name here.
  project: default 
  source:
    repoURL: https://github.com/thehulkhunts/ArgoCD.git
    targetRevision: feat/app-of-apps    #provide branch like master, feature, or tag, or hEAD
    path: app-of-apps # path to manifest files

  destination:
    server: https://kubernetes.default.svc #<replce-with-your-cluster-url>
    namespace: argocd # in which namespace you want to deploy an applications 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

#Custom resource definition for declarative argocd deployment for apps's