apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: java-app
      role: front-end
  template:
    metadata:
      labels:
        app: java-app
        role: frontend
    spec:
      containers:
      - name: java-app-ui
        image: vinayjadhav/java-app:v1.0.0
        #env:
        #- name: VITE_GEMINI_API
         # valueFrom:
          #  secretKeyRef:
           #   key: VITE_GEMINI_API
            #  name: dockerhub-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "256m"
        ports:
        - containerPort: 8080
