  apiVersion: v1
  kind: Service
  metadata:
    name: java-app-svc
    namespace: default
  spec:
    selector:
      app: java-app
      role: front-end
    ports:
    - port: 80
      targetPort: 8080
  