apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-list-generator
  namespace: argocd
spec:
  # The list generator lets you enumerate a static set of elements (apps).
  generators:
    - list:
        elements:   #changes this values according to your application paths.
          #- app: nginx
           # path: ui_approach/nginx     # path in repo for this app
          - app: online-shop
            path: app-of-apps/child-app   # path in repo for this app
          #- app: chaiapp
          # path: applicationsets/chai-app      # path in repo for this app
  # Template that will be used to generate individual Application CRs
  template:
    metadata:
      # name template uses the element key 'app'
      name: '{{app}}-list'
    spec:
      project: default
      source:
        repoURL: https://github.com/thehulkhunts/ArgoCD.git
        targetRevision: feat/applicationsets
        path: '{{path}}'                # resolved from element
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true