apiVersion: v1
kind: Service
metadata:
  name: svc-argocd-app-of-apps
  namespace: java-app
spec:
  selector:
    app.kubernetes.io: argocd-app-of-apps
    version: v.1.0.0
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
      