apiVersion: v1
kind: Service
metadata:
  name: svc-argocd-declarative-apps
  namespace: default
spec:
  selector:
    app.kubernetes.io: argocd
    version: v.1.0.0
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      